apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-api
  template:
    metadata:
      labels:
        app: device-api
    spec:
      containers:
      - name: app
        image: localhost:5000/device-api:latest
        ports:
        - containerPort: 9000