apiVersion: v1
kind: Service
metadata:
  name: device-api
  labels:
    app: device-api
spec:
  type: ClusterIP
  selector:
    app: device-api
  ports:
    - name: http
      port: 9000
      targetPort: 9000