apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-ingestor
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: telemetry-ingestor
  template:
    metadata:
      labels:
        app: telemetry-ingestor
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"