apiVersion: apps/v1
kind: Deployment
metadata:
  name: ota-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ota-controller
    spec:
      containers:
      - name: app
        image: localhost:5000/ota:latest