apiVersion: apps/v1
kind: Deployment
metadata:
  name: ota-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ota-controller
  template:
    metadata:
      labels:
        app: ota-controller
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: ota
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 7070
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]