apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ota-controller
spec:
  podSelector:
    matchLabels:
      app: ota-controller
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: device-api